// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voexhegvreyzivormccu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZXhoZWd2cmV5eml2b3JtY2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTA4MzksImV4cCI6MjA2NDY2NjgzOX0.yEXKl3KGmOP0lKw7rDm_Ys9TYc1Kyb8Yfy5nc8uBbS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);